import { safeString } from "./helpers.js";
import { normalizeAction } from "./normalize-action.js";
import { normalizePlaytest } from "./normalize-playtest.js";

export function normalizePlan(raw) {
  const actionList = Array.isArray(raw?.actions) ? raw.actions : [];
  const normalizedActions = [];
  for (const action of actionList) {
    const normalized = normalizeAction(action);
    if (normalized) {
      normalizedActions.push(normalized);
    }
  }

  const planPlaytest = normalizePlaytest(raw?.playtest || {});

  // Fix: if a run_playtest action exists but has empty scenario,
  // copy from plan-level playtest into it.
  for (const action of normalizedActions) {
    if (action.type === "run_playtest" && action.scenario) {
      if (!action.scenario.serverTest && planPlaytest.serverTest) {
        action.scenario.serverTest = planPlaytest.serverTest;
        action.scenario.clientTest = planPlaytest.clientTest;
        action.scenario.version = 2;
        action.scenario.goal = action.scenario.goal === "Generated playtest" || action.scenario.goal === "Playtest"
          ? planPlaytest.goal
          : action.scenario.goal;
        action.scenario.timeoutSeconds = planPlaytest.timeoutSeconds;
      }
    }
  }

  const out = {
    summary: safeString(raw?.summary, "Plan generated by uxRoai"),
    warnings: Array.isArray(raw?.warnings)
      ? raw.warnings.map((x) => safeString(x)).filter(Boolean)
      : [],
    actions: normalizedActions,
    playtest: planPlaytest,
  };

  if (typeof raw?.maxRetries === "number" && raw.maxRetries > 0) {
    out.maxRetries = Math.max(1, Math.min(20, Math.round(raw.maxRetries)));
  }

  return out;
}

export function fallbackPlanFromPrompt(prompt) {
  const escapedPrompt = prompt.replace(/\]\]/g, "] ]");

  return normalizePlan({
    summary: "Fallback plan generated because Claude is unavailable.",
    warnings: [
      "AI CLI not available or model request failed. Fallback mode is active.",
    ],
    actions: [
      {
        type: "create_instance",
        parentPath: "game.ReplicatedStorage",
        className: "Folder",
        name: "UxRoaIGenerated",
      },
      {
        type: "upsert_script",
        parentPath: "game.ReplicatedStorage.UxRoaIGenerated",
        runContext: "module",
        name: "FeatureSpec",
        source: `local FeatureSpec = {}
FeatureSpec.prompt = [[${escapedPrompt}]]
FeatureSpec.generatedAt = os.time()
return FeatureSpec`,
      },
      {
        type: "ensure_playtest_harness",
      },
    ],
    playtest: {
      goal: "Fallback smoke test",
      timeoutSeconds: 90,
      serverTest: 'task.wait(3)\nassert_exists("game.Workspace", "Workspace exists")',
    },
  });
}

export function fallbackPlaytestFromGoal(goal) {
  return normalizePlaytest({
    goal,
    timeoutSeconds: 120,
    serverTest: 'task.wait(3)\nassert_exists("game.Workspace", "Workspace exists")',
  });
}
